<?php

/**
 * @file
 * This is module sliderlayer.
 */

define('GAVIAS_SLIDERLAYER_GAVIAS_SLIDERLAYER_VERSION', '1.0');
define('GAVIAS_SLIDERLAYER_PATH', drupal_get_path('module', 'gavias_sliderlayer'));
module_load_include('php', 'gavias_sliderlayer', '/includes/functions');
module_load_include('php', 'gavias_sliderlayer', '/includes/model');
module_load_include('php', 'gavias_sliderlayer', '/includes/utilities');
module_load_include('php', 'gavias_sliderlayer', '/includes/frontend');

/**
 * Gavias sliderlayer theme.
 */
function gavias_sliderlayer_theme($existing, $type, $theme, $path) {
  $items['admin-form'] = [
    'variables' => [
      'content' => '',
    ],
    'path' => $path . '/templates/backend',
  ];

  $items['admin-global'] = [
    'variables' => [
      'content' => '',
    ],
    'path' => $path . '/templates/backend',
  ];

  $items['block-slider'] = [
    'variables' => [
      'content' => '',
    ],
    'path' => $path . '/templates/frontend',
  ];
  return $items;
}

/**
 * Gavias sliderlayer preprocess page.
 */
function gavias_sliderlayer_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'gavias_sliderlayer/gavias_sliderlayer.assets.frontend';
}

/**
 * Gavias sliderlayer styles.
 */
function gavias_sliderlayer_styles() {
  $variables = [
    'data' => [],
  ];
  Drupal::moduleHandler()->alter('sliderlayer_styles', $variables);

  return $variables['data'];
}

/**
 * Gavias sliderlayer update projects alter.
 */
function gavias_sliderlayer_update_projects_alter(&$projects) {
  unset($projects['gavias_sliderlayer']);
}
