_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  block: 0
  block_content: 0
  block_visibility_groups: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  fb_likebox: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  gavias_content_builder: 0
  gavias_hook_themer: 0
  gavias_sliderlayer: 0
  gavias_view: 0
  gaviasthemer: 0
  gin_lb: 0
  gin_toolbar: 0
  help: 0
  history: 0
  image: 0
  imce: 0
  jquery_ui: 0
  jquery_ui_datepicker: 0
  jquery_ui_tabs: 0
  jquery_ui_tooltip: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  menu_ui: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  rdf: 0
  search: 0
  shortcut: 0
  simplenews: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twitter_block: 0
  update: 0
  user: 0
  views_infinite_scroll: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  gavias_enzio: 0
  ebfactory: 0
  claro: 0
  gin: 0
profile: standard
